# CREATING ARRAYS

In [1]:
import numpy as np

In [2]:
#One dimensional array
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [3]:
#Two dimensional array
b = np.array([(1,2,3),(4,5,6)])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
#1D array of length 3 all values 0
c = np.zeros(3)
print(c)

[0. 0. 0.]


In [5]:
#3x4 array with all values 1
d = np.ones((3,4))
print(d)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
#5x5 array of 0 with 1 on diagonal(Identity matrix)
e = np.eye(5)
print(e)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [7]:
#Array of 6 evenly divided values from 0 to 100
f = np.linspace(0,100,6)
print(f)

[  0.  20.  40.  60.  80. 100.]


In [8]:
#Array of values from 0 to less than 10 with step 3
g = np.arange(0,10,3)
print(g)

[0 3 6 9]


In [9]:
#2x3 array with all values 8
h = np.full((2,3),8)
print(h)

[[8 8 8]
 [8 8 8]]


In [10]:
#4x5 array of random floats between 0-1
i = np.random.rand(4,5)
print(i)

[[0.23269987 0.92773836 0.11749911 0.19244228 0.13539155]
 [0.20610106 0.44854759 0.37476926 0.83999218 0.30605256]
 [0.47870812 0.0137647  0.45474563 0.84286232 0.10005479]
 [0.46784998 0.09358649 0.89971452 0.84519562 0.18842793]]


In [11]:
#6x7 array of random floats between 0-100
j = np.random.rand(6,7)*100
print(j)

[[78.80075016 37.38531551 82.72036847 11.42738602 64.65410142 27.24102301
  81.599467  ]
 [49.37642196 89.63792089 63.38912608 93.57869657 76.86993787 89.10827993
  53.05401844]
 [33.75597593 41.53092468 14.7314642  18.91579395 95.39173027 48.22430314
  84.78055162]
 [44.36033177 56.82616063 28.44886078  2.82020314 65.00305914 27.71116659
  59.48810762]
 [87.42636449 72.94221481 58.92472577 78.86185241 63.76289959 57.74058201
  11.83046659]
 [49.83993325 54.59039763  6.76089772 87.19288082 42.26668482 83.118066
  51.37796157]]


In [12]:
#2x3 array with random ints between 0-4
k = np.random.randint(5,size=(2,3))
print(k)

[[4 0 4]
 [0 4 3]]
