# Объединение и разделение массивов

### Функции hstack и vstack

Предположим у нас есть два двумерных массива:

In [1]:
import numpy as np

In [2]:
a = np.array([(1, 2), (3, 4)])
b = np.array([(5, 6), (7, 8)])
print(a, b, sep='\n')

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


Их можно объединить как по горизонтали, так и по вертикали, с помощью функций:

In [3]:
c = np.hstack([a, b])    # объединение по оси axis1 (размерность 2x4)
d = np.vstack([a, b])    # объединение по оси axis0 (размерность 4x2)
print(c, d, sep='\n')

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


Эти же операции можно выполнять и с многомерными массивами. Например, определим два трехмерных массива:

In [4]:
e = np.fromiter(range(18), dtype='int32')
f = np.fromiter(range(18, 36), dtype='int32')
e.resize(3, 3, 2)
f.resize(3, 3, 2)
print(e, f, sep='\n')

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]]
[[[18 19]
  [20 21]
  [22 23]]

 [[24 25]
  [26 27]
  [28 29]]

 [[30 31]
  [32 33]
  [34 35]]]


И выполним функции:

In [5]:
g = np.hstack([e, f])  # размерность 3x6x2
h = np.vstack([e, f])  # размерность 6x3x2
print(g, h, sep='\n')

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [18 19]
  [20 21]
  [22 23]]

 [[ 6  7]
  [ 8  9]
  [10 11]
  [24 25]
  [26 27]
  [28 29]]

 [[12 13]
  [14 15]
  [16 17]
  [30 31]
  [32 33]
  [34 35]]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]

 [[24 25]
  [26 27]
  [28 29]]

 [[30 31]
  [32 33]
  [34 35]]]


Как видите, здесь произошло формальное объединение по оси axis1 в функции hstack и по оси axis0 в функции vstack.

Разумеется, чтобы эти функции работали, размерность массивов по объединяемым осям должны совпадать.

Аналогичным образом происходит объединение и одномерных массивов:

In [6]:
i = np.fromstring('1 2 3 4', sep = ' ')
j = np.fromstring('5 6 7 8', sep = ' ')
k = np.hstack([i, j])
l = np.vstack([i, j])
print(k, l, sep='\n')

[1. 2. 3. 4. 5. 6. 7. 8.]
[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


### Функции column_stack и row_stack

Давайте теперь зададимся вопросом: как объединить наши два одномерных массива столбцами?
Для этого хорошо подходит функция column_stack():

In [7]:
print(np.column_stack([i, j]))

[[1. 5.]
 [2. 6.]
 [3. 7.]
 [4. 8.]]


Если с ее помощью объединять двумерные и многомерные массивы, то она будет давать тот же результат, что и функция hstack().

Другая аналогичная функция row_stack(), в принципе, делает то же самое, что и функция vstack() заметных отличий здесь нет. Ее можно использовать так:

In [8]:
print(np.row_stack([i, j]))

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


### Функция concatenate

Для объединения массивов вдоль строго определенной оси можно воспользоваться функцией concatenate(). Например, возьмем два трехмерных массива:

In [9]:
m = np.arange(1, 13)
n = np.arange(13, 25)
m.resize(3, 3, 2)
n.resize(3, 3, 2)
print(m, n, sep='\n')

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[ 0  0]
  [ 0  0]
  [ 0  0]]]
[[[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]

 [[ 0  0]
  [ 0  0]
  [ 0  0]]]


И объединим их по каждой из осей:

In [10]:
c0 = np.concatenate([m, n], axis=0) # размерность 6x3x2
c1 = np.concatenate([m, n], axis=1) # размерность 3x6x2
c2 = np.concatenate([m, n], axis=2) # размерность 3x3x4
print(c0, c1, c2, sep='\n')

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[ 0  0]
  [ 0  0]
  [ 0  0]]

 [[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]

 [[ 0  0]
  [ 0  0]
  [ 0  0]]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [13 14]
  [15 16]
  [17 18]]

 [[ 7  8]
  [ 9 10]
  [11 12]
  [19 20]
  [21 22]
  [23 24]]

 [[ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]]]
[[[ 1  2 13 14]
  [ 3  4 15 16]
  [ 5  6 17 18]]

 [[ 7  8 19 20]
  [ 9 10 21 22]
  [11 12 23 24]]

 [[ 0  0  0  0]
  [ 0  0  0  0]
  [ 0  0  0  0]]]
