# Транспонирование матриц и векторов

In [1]:
import numpy as np

In [2]:
#Очень часто в математических операциях требуется выполнять транспонирование матриц и векторов,
#то есть, заменять строки на столбцы. Например, если имеется матрица (двумерный массив),
#то операция транспонирования может быть реализована так:
a = np.array([(1, 2, 3), (1, 4, 9), (1, 8, 27)])
b = a.T
print(b)

[[ 1  1  1]
 [ 2  4  8]
 [ 3  9 27]]


In [3]:
#Транспонирование векторов работает несколько иначе. Предположим, имеется одномерный массив:
x = np.arange(1, 10)
#и мы выполняем операцию транспонирования:
x = x.T
print(x)

[1 2 3 4 5 6 7 8 9]


В результате ничего не изменилось: вектор как был строкой, так строкой и остался. Почему? Дело в том, что массив x имеет только одну размерность, поэтому здесь нет понятия строк и столбцов. Соответственно, операция транспонирования ни к чему не приводит. Чтобы получить ожидаемый эффект, нужно добавить к массиву еще одну ось.

# Добавление и удаление осей
Часто при работе с массивами NumPy требуется добавлять новые оси измерений и удалять существующие. Есть множество способов выполнять эти операции, но мы рассмотрим два наиболее распространенных с помощью функций:

np.expand_dims(a, axis) – добавление новой оси;

np.squeeze(a[, axis]) – удаление оси (без удаления элементов).

In [4]:
#Давайте предположим, что у нас имеется некий многомерный массив:
x_test = np.arange(32).reshape(8, 2, 2)
print(x_test)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]

 [[20 21]
  [22 23]]

 [[24 25]
  [26 27]]

 [[28 29]
  [30 31]]]


И нам потребовалось добавить еще одно измерение (ось), причем, в самое начало, то есть, ось axis0. Сейчас на этой оси 8 элементов – матриц 2x2, но мы хотим сделать четырехмерный массив, сохранив остальные три оси и их данные без изменений. Как раз это достаточно просто сделать с помощью функции expand_dims, следующим образом:

In [5]:
x_test4 = np.expand_dims(x_test, axis=0)
x_test4.shape

(1, 8, 2, 2)

Видим, что массив стал четырехмерным и первая добавленная ось axis0 содержит один элемент – трехмерный массив 8x2x2. При необходимости, мы всегда можем добавить новый элемент на эту ось:

In [6]:
c = np.append(x_test4, x_test4, axis=0)
c.shape

(2, 8, 2, 2)

или удалить ненужные элементы:

In [7]:
d = np.delete(c, 0, axis=0) #Здесь второй параметр 0 – индекс удаляемого элемента на оси axis0.
d.shape

(1, 8, 2, 2)

Если нам нужно добавить последнюю ось в массиве, то для этого можно записать такую команду:

In [8]:
d = np.expand_dims(x_test4, axis=-1)
d.shape

(1, 8, 2, 2, 1)

Следующая функция squeeze позволяет удалить все оси с одним элементом. Например, строчка:

In [9]:
e = np.squeeze(d)
e.shape

(8, 2, 2)

При необходимости, дополнительно мы можем самостоятельно указать оси, которые следует удалять.
Но, если указать ось с числом элементов больше 1, то возникнет ошибка.

# Объект newaxis
В NumPy добавлять новые оси иногда удобнее с помощью специального объекта np.newaxis. Например, пусть у нас есть одномерный массив:

In [10]:
f = np.arange(1, 10)
print(f)

[1 2 3 4 5 6 7 8 9]


У него одна ось – одно измерение. Добавим еще одну ось, допустим, в начало. С помощью объекта np.newaxis это можно сделать так:

In [11]:
g = f[np.newaxis, :]
print(g, g.shape, sep='\n')

[[1 2 3 4 5 6 7 8 9]]
(1, 9)


Или, можно прописать сразу две оси:

In [12]:
h = f[np.newaxis, :, np.newaxis]
print(h, h.shape, sep='\n')

[[[1]
  [2]
  [3]
  [4]
  [5]
  [6]
  [7]
  [8]
  [9]]]
(1, 9, 1)
