# Изменение формы массивов, добавление и удаление осей

In [1]:
import numpy as np

In [2]:
#Предположим, у нас имеется массив, состоящий из десяти чисел:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
#Для изменения формы этого массива, достаточно указать свойству shape кортеж с новыми размерами, например, так:
a.shape = 2, 5
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [4]:
#Если же требуется создать новое представление массива, сохранив прежнее, то следует воспользоваться методом reshape():
b = a.reshape(10)
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
#Ссылки b и a будут использовать одни и те же данные, то есть, изменение массива через b:
#Об этом всегда следует помнить.
b[0] = -1
print(a)

[[-1  1  2  3  4]
 [ 5  6  7  8  9]]


In [6]:
#Также следует помнить, что у свойства shape и метода reshape() размерность должна охватывать все элементы массива.
#Но допускается делать так(То же самое можно делать и в методе reshape()):
a.shape = -1, 2
print(a)

[[-1  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]]


In [7]:
#Если нам требуется многомерный массив преобразовать в обычный одномерный,
#то можно воспользоваться методом ravel(), который возвращает новое представление, не меняя текущего:
b = b.reshape(-1, 2)
c = b.ravel()
print(b, c, sep='\n')

[[-1  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]]
[-1  1  2  3  4  5  6  7  8  9]


In [8]:
#Если же нам нужно текущий массив преобразовать в одномерный, то это можно сделать так:
b.shape = -1
print(b)

[-1  1  2  3  4  5  6  7  8  9]


In [9]:
#Помимо свойства shape можно использовать метод resize,
#который выполняет подобную операцию с текущим массивом. Например:
a.resize(2, 5)
print(a)

[[-1  1  2  3  4]
 [ 5  6  7  8  9]]


In [10]:
#Mы все-таки можем выполнить такую операцию, указав дополнительно флаг refcheck=False:
a.resize(3, 3, refcheck=False)
print(a)

[[-1  1  2]
 [ 3  4  5]
 [ 6  7  8]]


In [11]:
#Или так:
a.resize(4, 5, refcheck=False)
print(a)

[[-1  1  2  3  4]
 [ 5  6  7  8  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]]
