### Объекты r_ и c_

Еще один способ объединения и создания массивов – это использование специальных объектов r_ и c_. Например, объект r_ создает копии массивов, следующими способами:

In [1]:
import numpy as np

In [2]:
a = np.r_[ [1, 2, 3], 4, 5]  # список + дополнительные элементы
b = np.r_[ 1:9, 90, 100] # срез + два элемента
c = np.r_[ np.array([1,2,3]), np.array([4,5,6])] # объединение двух массивов
d = np.r_[ [(1,2,3), (4,5,6)], [(7,8,9)] ]  # объединение двумерного и одномерного списков
print(a, b, c, d, sep='\n')

[1 2 3 4 5]
[  1   2   3   4   5   6   7   8  90 100]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


По аналогии работает и второй объект c_, только объединение выполняется по второй оси axis1:

In [3]:
e = np.c_[1:5]
f = np.c_[ [1, 2, 3], [4, 5, 6]]
g = np.c_[ [(1,2,3), (4,5,6)], [[7],[8]] ]
print(e, f, g, sep='\n')

[[1]
 [2]
 [3]
 [4]]
[[1 4]
 [2 5]
 [3 6]]
[[1 2 3 7]
 [4 5 6 8]]


### Разделение массивов

Массивы в NumPy можно не только объединять, но и разделять. Для этого существуют специальные функции hsplit и vsplit. Рассмотрим их работу на простых примерах. Пусть имеется одномерный массив из 10 элементов:

In [4]:
h = np.arange(10)
h

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

И мы хотим разделить его на две равные части. Это реализуется с помощью функции hsplit:

In [5]:
np.hsplit(h, 2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

которая возвращает список из двух массивов. Второй параметр 2 указывает число частей, на которые делится исходный массив. Причем, деление выполняется по горизонтали. Если в нашем примере указать 3 части, то возникнет ошибка. Также ошибка будет и при разбиении этого массива по вертикали, так как массив имеет одну горизонтальную ось. Чтобы вторая функция сработала, преобразуем массив a в вектор столбец:

In [6]:
h.shape = 10, -1
h

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [7]:
np.vsplit(h, 2)

[array([[0],
        [1],
        [2],
        [3],
        [4]]),
 array([[5],
        [6],
        [7],
        [8],
        [9]])]

Эти же функции можно использовать и с многомерными массивами, например, так:

In [8]:
i = np.arange(12)
i.resize(2, 6) # двумерный массив 2x6
 
j = np.hsplit(i, 2) # разбиение по горизонтали
k = np.vsplit(i, 2) # разбиение по вертикали
print(j, k, sep='\n')

[array([[0, 1, 2],
       [6, 7, 8]]), array([[ 3,  4,  5],
       [ 9, 10, 11]])]
[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]])]


### Функция array_split

Рассмотренные функции выполняют разбиение или по первой оси axis0 или по второй оси axis1. Но что если нам нужно выполнить разбиение по произвольной оси многомерного массива? Для этого существует функция array_split(). Ее работа аналогична рассмотренным выше функциям, только дополнительно указывается ось разбиения. Например:

In [9]:
l = np.arange(18)
l.resize(3, 3, 2)
 
m = np.array_split(l, 2, axis=2)
n = np.array_split(l, 3, axis=0)
o = np.array_split(l, 3, axis=1)
print(m, n, o, sep='\n')

[array([[[ 0],
        [ 2],
        [ 4]],

       [[ 6],
        [ 8],
        [10]],

       [[12],
        [14],
        [16]]]), array([[[ 1],
        [ 3],
        [ 5]],

       [[ 7],
        [ 9],
        [11]],

       [[13],
        [15],
        [17]]])]
[array([[[0, 1],
        [2, 3],
        [4, 5]]]), array([[[ 6,  7],
        [ 8,  9],
        [10, 11]]]), array([[[12, 13],
        [14, 15],
        [16, 17]]])]
[array([[[ 0,  1]],

       [[ 6,  7]],

       [[12, 13]]]), array([[[ 2,  3]],

       [[ 8,  9]],

       [[14, 15]]]), array([[[ 4,  5]],

       [[10, 11]],

       [[16, 17]]])]
