# Функции автозаполнения, создания матриц и числовых диапазонов


In [1]:
import numpy as np

In [2]:
#Возвращает новый массив заданного размера и типа данных, но без определенных значений. empty(shape, …)
a = np.empty(10, dtype='int32')
b = np.empty((3, 2), dtype='int32')
print(a, b, sep='\n')

[-1371734185       21849           0           0   -66832528       21852
   -66537376       21852 -1768362240       32665]
[[-1375325297       21849]
 [          0           0]
 [         32           0]]


In [3]:
#Возвращает квадратный массив размерностью nxn
#с единичными элементами по главной диагонали (остальные равны нулю). identity(n, …)
c = np.identity(5)
print(c)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [4]:
#Приводит входные данные object к матрице, если это возможно.
#Параметр object может быть строкой, списком или кортежем. mat(object, …)
d = np.mat('1 2 3 4')
e = np.mat('1, 2, 3, 4')
f = np.mat([(1, 2, 3), (4, 5, 6)])
print(d, e, f, sep='\n')

[[1 2 3 4]]
[[1 2 3 4]]
[[1 2 3]
 [4 5 6]]


In [5]:
#Формирует диагональную матрицу на основе списка или массива NumPy.
#В последних версиях возвращает копию массива (а не его представление). diag(list, …)
g = np.diag([1, 2, 3])
h = np.diag([(1,2,3), (4,5,6), (7,8,9)])
print(g, h, sep='\n')

[[1 0 0]
 [0 2 0]
 [0 0 3]]
[1 5 9]


In [6]:
#Формирует диагональную матрицу из списка list,
#который сначала сжимает до одной оси (преобразует в одномерный список или массив). diagflat(list, …)
i = np.diagflat([(1,2,3), (4,5,6), (7,8,9)])
print(i)

[[1 0 0 0 0 0 0 0 0]
 [0 2 0 0 0 0 0 0 0]
 [0 0 3 0 0 0 0 0 0]
 [0 0 0 4 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0]
 [0 0 0 0 0 6 0 0 0]
 [0 0 0 0 0 0 7 0 0]
 [0 0 0 0 0 0 0 8 0]
 [0 0 0 0 0 0 0 0 9]]


In [7]:
#Создает треугольный массив NxM с единицами на главной диагонали и ниже ее. tri(N, M=None, …)
j = np.tri(4)
print(j)

[[1. 0. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 1.]]


In [8]:
#Преобразует двумерный список или массив list в треугольную матрицу
#с нулевыми элементами выше главной диагонали. tril(list, …)
k = np.array( [(1,2,3), (4,5,6), (7,8,9)] )
print(np.tril(k))

[[1 0 0]
 [4 5 0]
 [7 8 9]]


In [9]:
#Преобразует двумерный список или массив list в треугольную матрицу
#с нулевыми элементами ниже главной диагонали. triu(list, …)
l = np.array( [(1,2,3), (4,5,6), (7,8,9)] )
print(np.triu(l))

[[1 2 3]
 [0 5 6]
 [0 0 9]]


In [10]:
#Создание матрицы Вандермонда из одномерного списка или массива list.
#Второй параметр N определяет число столбцов (по умолчанию формируется квадратная матрица). vander(list, N=None, …)
m = np.vander([1,2,3,4,5])
print(m)

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [11]:
#Возвращает одномерный массив с числами, равномерно распределенных по логарифмической шкале.
#logspace(start, stop, …)
n = np.logspace(0, 1, 4, dtype='float16')
print(n)

[ 1.     2.154  4.64  10.   ]


In [12]:
#Формирование чисел по геометрической прогрессии. geomspace(start, stop, …)
o = np.geomspace(1, 16, 5)
print(o)

[ 1.  2.  4.  8. 16.]
